name: scriptr
description: A script runner that makes developing simple CLIs easy.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.0.0
  meta: ^1.0.0
  http: ^1.0.0
  logging: ^1.0.0
  yaml: ^3.0.0
  json_annotation: ^4.7.0
  pub_semver: ^2.0.0
  equatable: ^2.0.0
  io: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^3.0.0
  test: ^1.16.0
