name: scriptr
description: A script runner that makes developing simple CLIs easy.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0
  meta: ^1.8.0
  http: ^0.13.5
  logging: ^1.1.0
  yaml: ^3.1.1
  json_annotation: ^4.7.0
  pub_semver: ^2.1.3
  interpolation: ^2.1.2
  equatable: ^2.0.5
  colorize: ^3.0.0
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
